publish_to: 'none' # Remove this line if you wish to publish to pub.dev
name: example
description: A new Flutter project.

# check for update based + build version
# This also update the server if needed!

# LASTED ANDROID: 305
# LASTED IOS: 307
version: 3.0.7+307
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.3+2
  auto_route: ^5.0.4
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^2.3.0
  dio: ^4.0.6
  dio_http_formatter: ^2.1.0
  dio_http2_adapter: ^2.0.0
  dartz: ^0.10.1

  #data class
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  firebase_storage: ^11.0.6
  provider: ^6.0.3
  firebase_auth: ^4.1.5
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.1.0
  intl: ^0.17.0

  #My
  bubble: ^1.2.1 # Chat Bubble uid
  uuid: ^3.0.6 # Generate token
  entry: ^0.0.7 # Widgets Appear
  age_calculator: ^1.0.0
  file: ^6.1.4
  image_picker: ^0.8.6
  dot_navigation_bar: ^1.0.1+4
  font_awesome_flutter: ^10.2.1
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
#  hive_generator: ^1.1.3
  path_provider: ^2.0.11
  string_to_hex: ^0.2.2
  shared_preferences: ^2.0.15
  palestine_console: ^0.0.10
  lazy_load_scrollview: ^1.3.0
  ansicolor: ^2.0.1
  rich_console: ^1.0.4
  badges: ^2.0.3
  widgets_to_image: ^0.0.2
  share_plus: ^6.3.0
  expandable_text: ^2.3.0
#  camera: ^0.10.1
#  camera: ^0.9.4+19
  camera:
    git:
      url: https://github.com/flutter/plugins
      path: packages/camera/camera
      ref: 9e46048ad2e1f085c1e8f6c77391fa52025e681f

  permission_handler: ^10.2.0
  video_player: ^2.4.10
  another_flushbar: ^1.12.29
  shimmer: ^2.0.0
  collection: ^1.16.0
  rive: ^0.10.1
  rive_splash_screen: ^0.1.1
  url_launcher: ^6.1.8
  firebase_messaging: ^14.2.1
#  apple_sign_in: ^0.1.0
  sign_in_with_apple: ^4.3.0
  package_info_plus: ^3.0.2
#  notification_permissions: ^0.6.1
  app_settings: ^4.2.0
  http: ^0.13.5
  # awesome_notifications: ^0.7.4+1
  transparent_image: ^2.0.0
  flutter_speed_dial: ^6.2.0
  auto_direction: ^0.0.6
  flutter_local_notifications: ^13.0.0

#  apple_sign_in: ^0.1.0
#  google_mobile_ads: ^2.3.0

#dependency_overrides:
#  camera:
#    git:
#      url: https://github.com/bottlepay/plugins.git
#      path: packages/camera/camera
#      ref: e1a4dba770da9bc3cf9f858bac6837083f8b9059

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.1.0+1


  #  flutter_launcher_name: ^0.0.1
#  flutter_launcher_name: # flutter pub get

# flutter pub run flutter_launcher_icons:main
# "WARNING: Icons with alpha channel are not allowed in the Apple App Store.
# Set "remove_alpha_ios: true" to remove it."
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"


flutter_gen:
  output: lib/common/service/mixins/
  integrations:
    flutter_svg: true


flutter:
  fonts:
    - family: RilTopia # BAHNSCHRIFT
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT_RILTOPIA.TTF
    - family: LexendBold
      fonts:
        - asset: assets/fonts/Lexend-Bold.ttf
    - family: LexendMedium
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
    - family: LexendRegular
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf

  assets:
    - assets/
    - assets/riv/
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/svg/icons/
  uses-material-design: true
