publish_to: 'none' # Remove this line if you wish to publish to pub.dev
name: example
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.3+2
  auto_route: ^5.0.4
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^2.3.0
  dio: ^4.0.6
  dio_http_formatter: ^2.1.0
  dio_http2_adapter: ^2.0.0
  dartz: ^0.10.1

  #data class
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  firebase_storage: ^11.0.6
  provider: ^6.0.3
  firebase_auth: ^4.1.5
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.1.0
  intl: ^0.17.0

  #My
  bubble: ^1.2.1 # Chat Bubble uid
  uuid: ^3.0.6 # Generate token
  entry: ^0.0.7 # Widgets Appear
  age_calculator: ^1.0.0
  file: ^6.1.4
  image_picker: ^0.8.6
  dot_navigation_bar: ^1.0.1+4
  font_awesome_flutter: ^10.2.1
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
#  hive_generator: ^1.1.3
  path_provider: ^2.0.11
  string_to_hex: ^0.2.2
  shared_preferences: ^2.0.15
  palestine_console: ^0.0.10
  lazy_load_scrollview: ^1.3.0
  ansicolor: ^2.0.1
  rich_console: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.1.0+1
  flutter_launcher_icons:

flutter_icons:
  ios: true
  android: "ic_launcher"
  image_path: "assets/messages_icon.png"

flutter_gen:
  output: lib/common/mixins/
  integrations:
    flutter_svg: true


flutter:
  fonts:
    - family: RilTopia # BAHNSCHRIFT
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT_RILTOPIA.TTF

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/svg/icons/
  uses-material-design: true
