// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzgymcOC7wUHjDBd_lA8ITFiI4R8kkt4Y',
    appId: '1:215350755755:web:05fb8ff41eaa913e5f52ee',
    messagingSenderId: '215350755755',
    projectId: 'pogo-shneor',
    authDomain: 'pogo-shneor.firebaseapp.com',
    storageBucket: 'pogo-shneor.appspot.com',
    measurementId: 'G-6VJC455MKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDnvQbIyMelt5CQB3HQDTYryzJQ86wgHo',
    appId: '1:215350755755:android:1703a75fef16fca55f52ee',
    messagingSenderId: '215350755755',
    projectId: 'pogo-shneor',
    storageBucket: 'pogo-shneor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7vH5BJEuQEL7XBhoLMXmMCagCFS8SwU',
    appId: '1:215350755755:ios:1b67907b9ea476e95f52ee',
    messagingSenderId: '215350755755',
    projectId: 'pogo-shneor',
    storageBucket: 'pogo-shneor.appspot.com',
    iosClientId: '215350755755-gmg79vsli3qa1n567pcdf26rend84p5p.apps.googleusercontent.com',
    iosBundleId: 'com.biton.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP7vH5BJEuQEL7XBhoLMXmMCagCFS8SwU',
    appId: '1:215350755755:ios:1b67907b9ea476e95f52ee',
    messagingSenderId: '215350755755',
    projectId: 'pogo-shneor',
    storageBucket: 'pogo-shneor.appspot.com',
    iosClientId: '215350755755-gmg79vsli3qa1n567pcdf26rend84p5p.apps.googleusercontent.com',
    iosBundleId: 'com.biton.example',
  );
}
