// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZPhyXw9HmsXJIYZqYtLLt4LW-Yt7tgc',
    appId: '1:751941760525:web:42ecad34cc07038f0d0744',
    messagingSenderId: '751941760525',
    projectId: 'biton-messanger',
    authDomain: 'biton-messanger.firebaseapp.com',
    storageBucket: 'biton-messanger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuG-vZF9NcsnuwFu_UM7OZX28IssbFyTI',
    appId: '1:751941760525:android:85ff7d910e6e63b00d0744',
    messagingSenderId: '751941760525',
    projectId: 'biton-messanger',
    storageBucket: 'biton-messanger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdM7gGQNeJN4LkzXaoHa9LlQhXuKPaFHk',
    appId: '1:751941760525:ios:0a7f1add50fb65ae0d0744',
    messagingSenderId: '751941760525',
    projectId: 'biton-messanger',
    storageBucket: 'biton-messanger.appspot.com',
    iosClientId: '751941760525-c36e2n06atejirfn2l1vg4rmino205o8.apps.googleusercontent.com',
    iosBundleId: 'com.biton.messaging',
  );
}
